Kotlin. Homework #1. Task #2
ArtyomKopan/Kotlin_HW pull request #2
Opened 2022-02-28 21:38 UTC by ArtyomKopan

2022-03-01 06:58 UTC, GirZ0n commented
Перед тем как назначать review, необходимо дождаться зелёной галочки от CI)) В этот раз прощаю, но в следующие раз это будет минус попытка)

2022-03-01 18:47 UTC, ArtyomKopan commented
Из-за чего может быть такое, что локально проект отлично собирается и запускается, а на гитхабе валится на стадии build?

2022-03-01 19:10 UTC, GirZ0n commented
> Из-за чего может быть такое, что локально проект отлично собирается и запускается, а на гитхабе валится на стадии build?

2022-03-01 19:11 UTC, GirZ0n commented
@ArtyomKopan, упс, случайно ПР закрыл)) Если верить CI, то всё падает из-за того, что ktlint нашёл ошибки со стилем кода)

2022-03-01 19:12 UTC, GirZ0n commented
Ты можешь нажать на крестик и посмотреть на логи.

2022-03-01 19:14 UTC, ArtyomKopan commented
Всего-то:) А я-то думал, что там что-то серьёзное. Мы каким кодстайлом пользуемся, стандартным идеевским 4-space?

2022-03-01 19:16 UTC, GirZ0n commented
Вроде да)

2022-03-01 19:18 UTC, ArtyomKopan commented
А что означает NoWildcardImports и ImportOrdering?

2022-03-01 19:23 UTC, GirZ0n commented
Ох, я сейчас заметил, что у вас не ktlint, а detekt) Но разницы особо нет. Ты можешь запускать его локально с помощью этой команды: `./gradlew detekt`. Добавь в идейке конфигурацию для этого)

`NoWildcardImports` -- нельзя использовать импорты, которые оканчиваются на * (собственно такие импорты и называются `wildcard`).
`ImportOrdering` -- неправильный порядок импортов.

Вообще описание всех ошибок есть в [доках](https://detekt.dev/index.html) детекта во вкладке `Rule sets`.

2022-03-01 19:58 UTC, ArtyomKopan commented
У меня в файле build.gradle.kts прописан detekt, но команда ./gradlew detekt не выполняется и выдаёт такую ошибку:
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

2022-03-01 20:12 UTC, GirZ0n commented
Ага, такое бывает. Попробуй погуглить как можно установить JAVA_HOME.

2022-03-01 21:00 UTC, ArtyomKopan commented
Я установил JAVA_HOME, но проблема никуда не исчезла, всё так же:(

2022-03-01 21:17 UTC, GirZ0n commented
Кажется он ругается на пробел между импортами.

2022-03-01 22:22 UTC, ArtyomKopan commented
Ура, получилось!

2022-03-02 07:34 UTC, GirZ0n commented
@ArtyomKopan, я могу проверять?)

2022-03-02 07:43 UTC, ArtyomKopan commented
да

2022-03-02 08:47 UTC, GirZ0n requested changes
Поменяй ещё название файла, оно сейчас не соответствует шаблону, указанному в документе с заданием)

2022-03-02 08:47 UTC, GirZ0n commented on src/test/kotlin/EratosphenTest.kt
> +internal class EratosphenTest {
Ну раз вы умеете работать с параметризованными тестами, то давай использовать их)

2022-03-02 08:47 UTC, GirZ0n commented on src/main/kotlin/task_1.2.kt
> +    }
Для таких целей лучше использовать функцию [`require`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/require.html#require).

2022-03-02 08:47 UTC, GirZ0n commented on src/main/kotlin/task_1.2.kt
> +    val primes = Array(n + 1) { true }
Лучше использовать primitive array, так как они эффективнее. В данном случае `BooleanArray`)

2022-03-02 08:47 UTC, GirZ0n commented on src/main/kotlin/task_1.2.kt
> +    for (p in 2..ceil(sqrt(n.toDouble())).toInt())
Да, в некоторых случаях можно не обрамлять тело цикла фигурными скобками, но чтобы код был согласованным давай всегда их использовать.

2022-03-02 08:47 UTC, GirZ0n commented on src/main/kotlin/task_1.2.kt
> +    val n = scan.nextInt()
А если я введу букву?)

2022-03-02 08:47 UTC, GirZ0n commented on src/main/kotlin/task_1.2.kt
> +    val n = scan.nextInt()
Вообще вместо `Scanner` можно использовать (и кажется, что даже удобнее) [`readline`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/read-line.html#readline))

2022-03-02 08:47 UTC, GirZ0n commented on src/main/kotlin/task_1.2.kt
> +        print("$i ")
У списков есть метод [`joinToString`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/join-to-string.html#jointostring).

2022-03-02 08:47 UTC, GirZ0n commented on src/main/kotlin/task_1.2.kt
> +            primeNumbers.add(i)
Можно в одну строчку написать с помощью [`mapIndexedNotNull`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/map-indexed-not-null.html#mapindexednotnull).

2022-03-02 08:47 UTC, GirZ0n commented on src/main/kotlin/task_1.2.kt
> +        }
Можно упростить, если добавить `step` в `for`.

2022-03-02 08:47 UTC, GirZ0n commented on src/main/kotlin/task_1.2.kt
> +    val primes = Array(n + 1) { true }
Название не очень хорошее, у тебя же булевый массив, поэтому он должен называться соответствующим образом. Например, `isPrime`.

2022-03-02 08:47 UTC, GirZ0n commented on src/main/kotlin/task_1.2.kt
> +fun getPrimeNumbers(n: Int): MutableList<Int> {
Группируй, пожалуйста, строки внутри функции, а то читать сплошной поток кода сложно)

2022-03-02 21:28 UTC, ArtyomKopan commented on src/main/kotlin/task_1.2.kt
> +            primeNumbers.add(i)
а как его написать? В списке методов к isPrime: BooleanArray IDEA его не показывает

2022-03-03 17:53 UTC, GirZ0n commented on src/main/kotlin/task_1.2.kt
> +            primeNumbers.add(i)
[mapIndexedNotNull](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/map-indexed-not-null.html#mapindexednotnull) доступен в версии 1.7, у тебя скорее всего в идейке 1.6, ты можешь просто обновить плагин)

Но если не хочешь, то можешь просто сначала применить [`mapIndexed`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/map-indexed.html#mapindexed), а затем [`filterNotNull`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/filter-not-null.html#filternotnull).

2022-03-03 21:17 UTC, ArtyomKopan commented on src/main/kotlin/task_1.2.kt
> +            primeNumbers.add(i)
А какой синтаксис у этого метода? Нигде нет примеров:(
Я написал import kotlin.collections.mapIndexedNotNull, это же правильный импорт?

2022-03-03 21:48 UTC, GirZ0n commented on src/main/kotlin/task_1.2.kt
> +            primeNumbers.add(i)
Синтаксис такой же как и у `mapIndexed`. Применяется функция, которая принимает индекс и элемент.

2022-03-03 21:51 UTC, GirZ0n commented on src/main/kotlin/task_1.2.kt
> +            primeNumbers.add(i)
Импортировать эту штуку не надо) Это метод списка)

2022-03-03 21:52 UTC, GirZ0n commented on src/main/kotlin/task_1.2.kt
> +            primeNumbers.add(i)
Если ты обновил версию Котлина, то все должно работать)

2022-03-03 22:06 UTC, ArtyomKopan commented on src/main/kotlin/task_1.2.kt
> +            primeNumbers.add(i)
Котлин у меня стоит 1.6, но mapIndexedNotNull всё равно нет
Как здесь будет правильно применить фильтр?
`val primeNumbers = isPrime.mapIndexed{ index, b -> index }.filterNotNull()`

2022-03-04 06:37 UTC, GirZ0n commented on src/main/kotlin/task_1.2.kt
> +            primeNumbers.add(i)
А ты поменял в `build.gradle.kts` версию котлина?

Применяем как-то так:
```kotlin
primeNumbers.mapIndexed { index, value -> if (value) index else null }.filterNotNull()
```

2022-03-05 19:26 UTC, GirZ0n commented
@ArtyomKopan, ты будешь ещё что-то подправлять или мне можно уже проверять?) Просто ты вроде всё исправил, но не запросил повторное ревью)

2022-03-05 19:28 UTC, ArtyomKopan commented
Да, можно проверять. Я не знал, что нужно запрашивать повторное, раньше у нас такого не было:)

2022-03-05 19:34 UTC, GirZ0n commented
@ArtyomKopan, там справа в `Reviewers` около моего ника есть кнопочка для повторного запроса ревью)

2022-03-06 10:19 UTC, GirZ0n requested changes
Балдёж! Оставил несколько небольших замечаний)

2022-03-06 10:19 UTC, GirZ0n commented on src/main/kotlin/Homework1/task_2.kt
> +    return isPrime.mapIndexed { index, value -> if (value) index else null }.filterNotNull()
Я понял почему ты не мог вызвать здесь `mapIndexedNotNull`. Почему-то этого метода нет у primitive arrays, так что давай `BooleanArray` поменяем на `MutableList`.

2022-03-06 10:19 UTC, GirZ0n commented on src/main/kotlin/Homework1/task_2.kt
> +    for (p in 2..ceil(sqrt(n.toDouble())).toInt()) {
Кажется `p` это не очень хорошее название)

2022-03-06 10:19 UTC, GirZ0n commented on src/main/kotlin/Homework1/task_2.kt
> +        val n = readLine()!!.toInt()
Нужно всеми силами избегать `!!`. В данном случае ты можешь написать так: `readLine()?.toIntOrNull()`. Таком образом, если возникнет какая-то проблема со считыванием или конвертацией, то в `n` запишется `null`. Ну и далее ты просто проверяешь `n` на `null`, если это так то выводишь сообщение и завершаешь работу. Компилятор поймёт, что после этой проверки `n` уже точно не `null`, поэтому ты сможешь использовать его как обычно.

2022-03-06 10:19 UTC, GirZ0n commented on src/main/kotlin/Homework1/task_2.kt
> +    } catch (e: NumberFormatException) {
И вот тут ты вместо `NumberFormatException` должен ловить исключение, которое порождает `require` (`IllegalArgumentException`). Потому что сейчас, если ввести отрицательное число, то в пользователя кидается ошибка)

2022-03-06 10:19 UTC, GirZ0n commented on src/main/kotlin/Homework1/task_2.kt
> +        println(e)
Лучше `e.message`, чтобы пользователь не пугался при виде названия ошибки))

2022-03-06 10:19 UTC, GirZ0n commented on src/test/kotlin/Homework1/EratosphenTest.kt
> +
Ну эти тесты проверяют одно и тоже, так что давай оставим что-то одно)

2022-03-06 10:19 UTC, GirZ0n commented on src/test/kotlin/Homework1/EratosphenTest.kt
> +
Ещё можно проверять сообщение исключения. Это полезно в том случае, если прога может кинуть одно и тоже исключение, но с разными сообщениями. Как это сделать написано вот [тут](https://www.baeldung.com/kotlin/assertfailswith#1-asserting-exception-attributes). 

P.S. Только не передавай явно `block`. Там можно написать вот так:
```kotlin
fun givenInvalidNumericFormat_thenThrowsException() {
    val exception = assertFailsWith<NumberFormatException> { Integer.parseInt("abcdefgh") }
    assertEquals(exception.message, "For input string: \"abcdefgh\"")
}
```

2022-03-06 10:19 UTC, GirZ0n commented on src/test/kotlin/Homework1/EratosphenTest.kt
> +            Arguments.of(listOf<Int>(), 1),
Для создания пустых списков можно (и нужно) использовать `emptyList`.

2022-03-06 17:39 UTC, ArtyomKopan commented on src/main/kotlin/Homework1/task_2.kt
> +    return isPrime.mapIndexed { index, value -> if (value) index else null }.filterNotNull()
а не проще оставить всё как есть?) Опять же, производительность будет лучше

2022-03-06 17:44 UTC, GirZ0n commented on src/main/kotlin/Homework1/task_2.kt
> +    return isPrime.mapIndexed { index, value -> if (value) index else null }.filterNotNull()
В целом да, можно оставить и так)

2022-03-07 11:23 UTC, ArtyomKopan commented on src/main/kotlin/Homework1/task_2.kt
> +        val n = readLine()!!.toInt()
@GirZ0n В таком случае здесь можно убрать try-catch? Ведь если мы введём что-то плохое, например, букву, то в n запишется null, мы проверим, что это так, и кинем пользователю сообщение. А в дальнейшем мы уже уверены, что n: Int и Illegal argument exception уже не возникнет, разве что уже в require в функции getPrimeNumbers

2022-03-07 11:37 UTC, GirZ0n commented on src/main/kotlin/Homework1/task_2.kt
> +        val n = readLine()!!.toInt()
Да, считывание `n` можно вынести, но всё остальное придётся оставить, так как может появится `IllegalArgumentException`)

2022-03-07 11:38 UTC, GirZ0n commented on src/main/kotlin/Homework1/task_2.kt
> +        val n = readLine()!!.toInt()
`IllegalArgumentException` появится если ввести -1. Но в целом ты можешь добавить проверку в `main`, что `n` неотрицательно и тогда можно вообще убрать try)

2022-03-08 12:48 UTC, GirZ0n approved these changes
Ты меня не так понял) Убирать `require` из `getPrimeNumbers` не надо) Я имел в виду, что ты в `main` можешь обойтись без `try`, если заранее проверишь все условия из `require`. Так что надо вернуть `require` и соответствующий тест с проверкой сообщения (как я написал тебе ранее).

А так в целом всё норм) Не забывай только ставить фигурные скобки. Сейчас `if`, который на 22 строке в `task_2.kt` без них)

Третье ревью делает Егор, так что жди его)

2022-03-09 13:58 UTC, GirZ0n commented on src/test/kotlin/Homework1/EratosphenTest.kt
> +
@ArtyomKopan, здесь я написал просто пример)) У тебя должно быть по-другому))

2022-03-09 13:59 UTC, GirZ0n commented on src/test/kotlin/Homework1/EratosphenTest.kt
> +
Просто в той статье, которую я скинул не очень хорошо написано)

2022-03-09 14:04 UTC, ArtyomKopan commented on src/test/kotlin/Homework1/EratosphenTest.kt
> +
А зачем в моей программе вообще нужно проверять сообщения исключений? Как бы в результате всех проверок исключение может бросить только `require`

2022-03-09 14:05 UTC, ArtyomKopan commented on src/test/kotlin/Homework1/EratosphenTest.kt
> +
Или мы это делаем как бы с заделом на будущее, если вдруг придётся переиспользовать?

2022-03-09 14:10 UTC, GirZ0n commented on src/test/kotlin/Homework1/EratosphenTest.kt
> +
Да и для этого тоже. Ну то есть у тебя может быть несколько частей в коде, которые кидают одно и тоже исключение. Поэтому хотелось как-то различать эти случаи. Это мы и делаем с помощью проверки сообщения)

2022-03-09 14:11 UTC, ArtyomKopan commented on src/test/kotlin/Homework1/EratosphenTest.kt
> +
не могу понять, как нужно это реализовать применительно к моему коду. Нужно сделать из этого параметризованнный тест?

2022-03-09 14:12 UTC, GirZ0n commented on src/test/kotlin/Homework1/EratosphenTest.kt
> +
ВОЗМОЖНО я не прав и проверять сообщения бессмысленно, но мне кажется лучше проверить, чем не проверить))

2022-03-09 14:15 UTC, GirZ0n commented on src/test/kotlin/Homework1/EratosphenTest.kt
> +
Всё очень просто) 
```kotlin
@Test
fun `ochen_krutoe_nazvanie`() {
    val exception = assertFailsWith<IllegalArgumentException> { getPrimeNumbers(-42) }
    assertEquals(exception.message, "Граница должна быть положительным числом!")
}
```

2022-03-10 15:45 UTC, SpirinEgor approved these changes

2022-03-10 15:45 UTC, SpirinEgor commented on src/main/kotlin/Homework1/task_2.kt
> +    for (possiblyPrime in 2..ceil(sqrt(n.toDouble())).toInt()) {
На будущее, тут лучше ограничивать `possiblePrime * possiblePrime < n`. Так не будет возьни с корнями и кастами туда-сюда

2022-03-10 15:46 UTC, merged