Kotlin. Homework #1. Task #3
ArtyomKopan/Kotlin_HW pull request #3
Opened 2022-03-04 20:39 UTC by ArtyomKopan

Я написал код, но не знаю, как грамотно написать тесты: то ли тестировать все функции класса PerformedCommandStorage по отдельности (но как тогда передать в эти тесты класс?), то ли тестировать всё сразу (как-то (опять же, не знаю как) передавать программе входные данные и проверять выходные).
Помогите разобраться, пожалуйста!

2022-03-05 09:27 UTC, illided commented
> Я написал код, но не знаю, как грамотно написать тесты: то ли тестировать все функции класса PerformedCommandStorage по отдельности (но как тогда передать в эти тесты класс?), то ли тестировать всё сразу (как-то (опять же, не знаю как) передавать программе входные данные и проверять выходные). 

Ну, тут основная проблема, что ты сделал свой класс практически не тестируемым) Как ты узнаешь какие числа у тебя в классе если он исключительно печатает их в консоль? 

Это неудобно даже в плане использования. Представь я делаю приложение для заметок и хочу чтобы можно было записи добавлять, менять местами и в случае чего отменять последнее действие. Вот как мне твой класс использовать?) Как узнать какие у меня сейчас заметки? 

Решение будет достаточно простым: убрать функции принта и пусть класс просто отдает списки. Если очень хочется все круто сделать можно даже отнаследоваться от Collection (но за это не дадут баллы, только почет и уважение :-) )

Потом просто точно так же как и в 1.2 пишешь тесты. Внутри тестов создаешь свой Storage, делаешь на нем комманды, получаешь список и сравниваешь с тем который должен быть.

А еще: дай сначала CI прогнаться и посмотреть упадет или нет, а потом уже отправляй review.

2022-03-06 20:22 UTC, ArtyomKopan commented
@illided я не могу отправить код на ревью из-за того, что detekt ругается на имя класса PerformedCommandStorage и на имя пакета. Как это можно исправить?

2022-03-07 11:13 UTC, illided commented
> @illided я не могу отправить код на ревью из-за того, что detekt ругается на имя класса PerformedCommandStorage и на имя пакета. Как это можно исправить?

Вообще можно загуглить ошибку которую он выдает. Просто вводишь <ошибка нейм> detekt и тебе выдадут огромный рулсет где все отсортировано по категориям и названиям, и написано что конкретное правило означает.

Вот например MatchingDeclarationName: https://detekt.dev/naming.html#matchingdeclarationname

2022-03-08 08:03 UTC, illided commented
Я не совсем понимаю когда можно будет смотреть твою ДЗ :)
Отпишись мне пожалуйста когда будет готово и убери пока label если еще делаешь.

2022-03-08 08:17 UTC, ArtyomKopan commented
Уже можно смотреть

2022-03-08 08:50 UTC, illided requested changes
Очень плохая идея пихать все в один файл. Лучше положить storage отдельно, если его захочется потом переиспользовать или изменить.

2022-03-08 08:50 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +        Collections.swap(numbers, firstIndex, secondIndex)
Уже третий swap за сегодня) В задании написано: переместить элемент с i на j позицию (обратное действие – переместить элемент с j на i позицию)

2022-03-08 08:50 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +        actions.add("ADD_HEAD")
Лучше сделать Enum вместо строк

2022-03-08 08:50 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +    fun getNumbers(): MutableList<Int> = numbers
Вместо такой функции лучше сделать поле и соответствующие геттер.
https://kotlinlang.org/docs/properties.html

2022-03-08 08:50 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +        if (actions.isEmpty())
В задании сказано: В случае, если действий еще совершенно не было, бросить соответствующую ошибку.

2022-03-08 08:50 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +            "ADD_HEAD" -> storage.addHead(command.second!!)
А зачем тут вообще nullable аргументы?

2022-03-08 08:50 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +                commandBuffer.add(Triple(command, scan.nextInt(), null))
Вот зачем! Ну такое. Добавлять новые команды тут будет сущим кошмаром. Лучше уж передавать список аргументов.

2022-03-08 08:50 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +    return commandBuffer
Если честно то я вообще не понимаю логики набирать команды в буфер а потом их выполнять (что говорится offline). Ты же уже написал замечательный сторадж который умеет все отменять, почему не сразу применять все операции на нем?

2022-03-08 08:50 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +                if (firstIndex >= numberListLength || secondIndex >= numberListLength) {
А если я введу -100?

2022-03-08 08:50 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +            else -> Collections.swap(numbers, swaps.removeLast().first, swaps.removeLast().second)
Воу! То есть если мы добавим какую то новую команду и забудем ее сюда написать то сторадж будет на нее свапать? Звучит как надежный источник багов и головной боли)

2022-03-08 08:53 UTC, ArtyomKopan commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +    return commandBuffer
тогда я не знаю, как это тестировать

2022-03-08 08:56 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +    return commandBuffer
Хороший вопрос. Я думаю вам пока можно не тестировать сам CLI. 
То есть достаточно тестов на сам сторадж: добавлять в него числа, убирать, свапать  и смотреть получившийся список.

2022-03-09 14:18 UTC, ArtyomKopan commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +        Collections.swap(numbers, firstIndex, secondIndex)
@illided можно ли в функции перемещения аргумента не обрабатывать исключение, а обойтись `require`'ом?

2022-03-09 20:59 UTC, ArtyomKopan commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +        if (actions.isEmpty())
@illided норм, если я вместо того, чтобы бросить ошибку, вывожу сообщение для пользователя в консоль?

2022-03-09 21:01 UTC, ArtyomKopan commented
@illided У меня не получается протестировать исключение в move.
Я перехватываю его так:
```
catch (e: IndexOutOfBoundsException) {
            println("Команда MOVE некорректна: один из индексов не существует! ${e.message}")
        }
```
 а в тесте пишу так:
```
@Test
fun `incorrect move element test`() {
        val storage = PerformedCommandStorage()
        assertThrows<IndexOutOfBoundsException> { storage.moveElement(-1, 10) }
    }
```
и в итоге этот тест фейлится с сообщением, что исключение не было брошено.
Это происходит из-за того, что я перехватываю его и вывожу на экран? Как можно сделать, чтобы assertThrows всё же видел исключение в таком случае?

2022-03-11 08:16 UTC, illided commented
> @illided У меня не получается протестировать исключение в move. Я перехватываю его так:
> 
> ```
> catch (e: IndexOutOfBoundsException) {
>             println("Команда MOVE некорректна: один из индексов не существует! ${e.message}")
>         }
> ```

А зачем ты его перехватываешь и что то печатаешь? Если этот catch находится в самом storage то он не нужен, пусть плюется исключениями. А если этот catch в коде который отвечает за общение между storage и юзером, то такой код тестировать пока не нужно

2022-03-11 08:18 UTC, illided commented
Еще кстати предупрежу, что просят Action написать в виде классов (которые могут сами применять и отменять действие), так что скорее всего придется это исправить :(

2022-03-11 09:03 UTC, ArtyomKopan commented
@illided То есть для каждого действия нужно написать свой класс?

2022-03-19 08:20 UTC, illided requested changes
Разбей еще больше по файлам, так чуть читабельнее будет и легче поддерживать

Сори что не отвечал на сообщения, уведомление не заметил :(
В таких случаях можешь на почту мне если что писать или в телегу `@illided`

2022-03-19 08:20 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +    val moves = mutableListOf<Pair<Int, Int>>()
А зачем вообще этот список если ты хранишь все действия в классах?
Оттуда и можно индексы старые доставать

2022-03-19 08:20 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +    val moves = mutableListOf<Pair<Int, Int>>()
А. Это енам. Почему тогда не класть `Action` и избавиться от енама вообще?)

2022-03-19 08:20 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +    override fun doAction(storage: PerformedCommandStorage, arguments: List<Int>) {
Не нравится мне что аргументы вот так передаются. Давай сделаем это полями конструктора в конкретных реализациях
Что то типо
`class ChangePosition(from: Int, to: Int) : Action`

2022-03-19 08:20 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +        val firstIndex = arguments.first()
Не `first` и `second` а `from` и `to` :)
С ума ведь сойдешь потом дебажить

2022-03-19 08:20 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +            println("Список команд пуст, отменять нечего")
Давай классы не будут ничего печатать в консоль. Лучше кинуть исключение а там уже кто то кто с пользователем работает разберется

2022-03-19 08:20 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +fun commandProcessing(): MutableList<Int> {
Функции называем глаголами а классы существительными

2022-03-19 08:20 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +                    println("Команда MOVE некорректна: один из индексов отрицателен!")
Давай команда сама разберется)
А то так каждую обрабатывать с ума сойдешь

2022-03-19 08:20 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +                val action = AddHead()
Не нравится мне это. Почему просто у последнего Action не вызвать cancel?

2022-03-23 13:23 UTC, illided requested changes
Уже очень хорошо. Кидаю тебя на Егора

2022-03-23 13:23 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +    val actions = mutableListOf<Action>()
Вот это надо сделать приватным

2022-03-23 13:23 UTC, illided commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +    val numbers = mutableListOf<Int>()
А вот это можно разделить на два проперти
Одно приватное мутабельное, а другое публичное просто с гетером

2022-03-23 13:23 UTC, illided commented on src/main/kotlin/homework1/Actions.kt
> +
Не надо так много пустых строк)

2022-03-23 13:23 UTC, illided commented on src/main/kotlin/homework1/Actions.kt
> +
Вот здесь тем более. Оставь только между функциями

2022-03-23 13:23 UTC, illided commented on src/main/kotlin/homework1/Actions.kt
> +        return index >= 0 && index < storage.numbers.size
В таких случаях можно написать просто через равно

2022-03-23 13:23 UTC, illided commented on src/main/kotlin/homework1/Actions.kt
> +            throw IllegalArgumentException("Команда MOVE некорректна: один из индексов выходит за границы списка")
Давай сделаем через `require`

2022-03-23 13:23 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +fun commandProcess(): MutableList<Int> {
Все еще не глагол)

2022-03-23 13:23 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +            "ADD_HEAD" -> storage.addAction(AddHead(scan.nextInt()))
Сделай лучше через енам

2022-03-23 13:23 UTC, illided commented on src/main/kotlin/homework1/task_3.kt
> +            "ADD_HEAD" -> storage.addAction(AddHead(scan.nextInt()))
Конкретно часть где ты общаешься с пользователем

2022-03-23 13:25 UTC, illided approved these changes
Забыл апрув сделать от себя)

2022-03-25 10:00 UTC, SpirinEgor requested changes
Надо поправить интерфейс Actions и учесть все комментарии Ильи

2022-03-25 10:00 UTC, SpirinEgor commented on src/main/kotlin/homework1/Actions.kt
> +    fun doAction(storage: PerformedCommandStorage)
То есть storage хранит лист Actions, который этот storage используют. Получается какая-то циклическая зависимость. По-хорошему, надо это сделать в одну сторону только, например, storage агрегирует в себе Action и только. Тут ещё проблема в том, что по сути action можно к любому листу/массиву применять, а ты это ограничил.

В общем, пусть Action принимает лист чисел

2022-03-25 10:00 UTC, SpirinEgor commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +    val actions = mutableListOf<Action>()
+1

2022-03-25 10:00 UTC, SpirinEgor commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +    val numbers = mutableListOf<Int>()
И публичное уже не мутабельное, на всякий уточню

2022-03-25 10:00 UTC, SpirinEgor commented on src/main/kotlin/homework1/task_3.kt
> +            "ADD_HEAD" -> storage.addAction(AddHead(scan.nextInt()))
Да, пусть список CLI команд будет enum

2022-04-03 14:07 UTC, ArtyomKopan commented on src/main/kotlin/homework1/PerformedCommandStorage.kt
> +    val numbers = mutableListOf<Int>()
А какое из них приватное, а какое публичное?
И тогда непонятно, как мы сможем добавлять команды/числа в иммутабельный список?

2022-04-07 15:14 UTC, SpirinEgor approved these changes

2022-04-07 15:14 UTC, merged