Kotlin. Test #1. Task 1. Копань Артём
ArtyomKopan/Kotlin_HW pull request #4
Opened 2022-03-28 11:54 UTC by ArtyomKopan

2022-04-05 10:44 UTC, SpirinEgor requested changes
Совсем всё грустно :(
CI падает, тестов нет, по коду тоже можно улучшить местами

2022-04-05 22:22 UTC, ArtyomKopan commented
Но ведь один тест всё-таки есть, и он даже работает:)  А остальные делаются по такому же шаблону

А что касается CI - мне кажется странным требовать соблюдение всех мелочных требований detekt на контрольной, в условиях ограниченного времени

2022-04-05 22:23 UTC, ArtyomKopan commented
Но ведь один тест всё-таки есть, и он даже правильно работает:) А остальные делаются по такому же шаблону

А что касается CI - мне кажется странным требовать соблюдение всех мелочных требований detekt на контрольной, в условиях ограниченного времени

2022-04-06 12:01 UTC, GirZ0n commented
@ArtyomKopan

Два года назад тоже через это всё проходил, поэтому совет: перед КР заранее открой IDE, создай файлики (с исходниками и с тестами), напиши там какой-то дефолтный код (например, вычисление факториала и тест для этого) и проверь что всё работает. Так тебе не нужно будет тратить на КР время для решения неожиданных проблем.

Ну и конечно же не нужно пытаться выполнить сразу все задания, лучше сделать одно, но точно правильно, чем все, но не правильно)

И ещё лучше минут 10-15 сначала потратить на то, чтобы понять, что требуется в каждом задании, и затем распланировать своё время: 
1) Порядок выполнения задач;
2) Сколько на каждое стоит потратить;
3) Что делать, если во время не уложился.

Ну и по поводу требований: на КР обычно не требуют прям супер-пупер крутого кода как в домахе, главное чтобы он работал, проходил тесты и выглядел +- адекватно)

2022-05-20 21:05 UTC, closed without merging