Kotlin. Homework #3. Task #1
ArtyomKopan/Kotlin_HW pull request #5
Opened 2022-04-14 22:23 UTC by ArtyomKopan

2022-04-16 13:58 UTC, GirZ0n requested changes
Несбалансированное дерево получилось :(
![image](https://user-images.githubusercontent.com/55441714/163677430-164f79f4-e427-49a4-a18c-dbe1d9dc03b3.png)

2022-04-16 13:58 UTC, GirZ0n commented on src/main/kotlin/Homework3/AVLTreeNode.kt
> +const val LEFT_REBALANCED_VALUE = -2
А зачем другим видеть эти константы?) Перемести их внутрь `AVLTreeNode` в `companion object`.

2022-04-16 13:58 UTC, GirZ0n commented on src/main/kotlin/Homework3/AVLTreeNode.kt
> +            key > this.key ->
А скобочки где? :(

2022-04-16 13:58 UTC, GirZ0n commented on src/main/kotlin/Homework3/AVLTreeNode.kt
> +            else ->
И тут тоже скобочек нету :(

2022-04-16 13:58 UTC, GirZ0n commented on src/main/kotlin/Homework3/AVLTree.kt
> +    override fun isEmpty() = treeRoot == null
Кажется, что лучше проверять `size`: `size == 0`.

2022-04-16 13:58 UTC, GirZ0n commented on src/main/kotlin/Homework3/AVLTree.kt
> +    override val entries = mutableSetOf<MutableMap.MutableEntry<K, V>>()
Лучше переопредели геттеры у этих полей. При обращении к полю обходи дерево и собирай нужные значения.

2022-04-16 13:58 UTC, GirZ0n commented on src/test/kotlin/Homework3/AVLTreeTest.kt
> +internal class AVLTreeTest {
Используй параметризованные тесты.

2022-04-16 13:58 UTC, GirZ0n commented on src/main/kotlin/Homework3/AVLTree.kt
> +        val removedNode = treeRoot?.remove(key)
Кажется, что то, что хранит эта переменная, не очень совпадает с названием.

2022-04-16 16:37 UTC, ArtyomKopan commented on src/main/kotlin/Homework3/AVLTree.kt
> +    override val entries = mutableSetOf<MutableMap.MutableEntry<K, V>>()
Разве в этом случае не снизится производительность?

2022-04-16 17:13 UTC, GirZ0n commented on src/main/kotlin/Homework3/AVLTree.kt
> +    override val entries = mutableSetOf<MutableMap.MutableEntry<K, V>>()
Ну вообще да снизится, но кажется что не очень важно насколько быстро мы будем получать значения этих полей)

2022-04-19 21:42 UTC, ArtyomKopan commented
@GirZ0n Не могу понять, почему дерево не балансируется. Проверил, всё по алгоритму, как должно быть. В прошлом семестре мы делали АВЛ на C, я сверил код - всё так же, причём на C отлично работает. Пробовал по разному изменять balance - не помогает:(

2022-04-20 08:45 UTC, GirZ0n commented
@ArtyomKopan. Могу в пятницу посмотреть, но пока можешь попробовать, например, делать все операции не in-place как у тебя сейчас, а возвращать изменённые ноды. Возможно это поможет :)

2022-04-22 09:53 UTC, GirZ0n commented
@ArtyomKopan, получилось?)

2022-04-22 09:56 UTC, ArtyomKopan commented
Сделал операции возвращающими вершину, но так и не балансируется...

2022-04-22 10:05 UTC, GirZ0n commented
@ArtyomKopan, А можешь куда-нибудь выложить этот код? Например, можно на Github Gist залить.

2022-04-22 10:06 UTC, ArtyomKopan commented
Сейчас код выглядит вот так: https://pastebin.com/bB6H0YYU , https://pastebin.com/492khJ1p

2022-04-22 12:03 UTC, GirZ0n commented
@ArtyomKopan, я всё же не успею сегодня посмотреть :( Но точно сделаю это на выходных (постараюсь завтра).

2022-04-23 12:57 UTC, GirZ0n commented
@ArtyomKopan. Так, смотри:
1. Добавь функции `rotateLeftRight` и `rotateRightLeft`. С ними становится легче разобраться с балансировкой.
2. Соответствующим образом поправь функцию `balance`:
```kotlin
RIGHT_REBALANCED_VALUE -> {
    if ((right?.balanceFactor ?: -1) < 0) {
        this.rightLeftRotate()
    } else {
        this.rotateLeft()
    }
}
// и ещё одна ветка
```
3. Поменяй дефолтные значения в случае, если `left` или `right` отсутствуют. Следует использовать -1, а не 0.
4. Функции связанные с добавлением и удалением значений вынеси лучше в класс самого дерева и соответственно передавай в них ноду. Так они более приятно реализуются. Например, добавления элемента сведётся вот к такому коду:
```kotlin
fun insert(node: AVLTreeNode<K, V>?, key: K, value: V): AVLTreeNode<K, V> {
    node ?: return AVLTreeNode(key, value)

    when {
        key == node.key -> node.value = value
        key > node.key -> node.right = insert(node.right, key, value)
        key < node.key -> node.left = insert(node.left, key, value)
    }

    return node.balance()
}

override fun put(key: K, value: V): V? {
    val oldValue = treeRoot?.get(key)
    treeRoot = insert(treeRoot, key, value)
    return oldValue
}
```

2022-04-26 20:13 UTC, ArtyomKopan commented
Спасибо!

2022-04-26 20:14 UTC, ArtyomKopan commented
Оказывается, балансировка была правильной (так что я обошёлся без rightLeftRotate и leftRightRotate), всё дело было в добавлении вершин. После того, как добавил insert, всё заработало)

2022-04-30 13:53 UTC, GirZ0n requested changes
Вот чуть-чуть недобалансировался
![image](https://user-images.githubusercontent.com/55441714/166108001-f9f53bf2-85b5-407e-97a1-314597057e1b.png)

И ещё вот такая странная вещь o_0:
![image](https://user-images.githubusercontent.com/55441714/166108161-bb4b437b-cac4-4cc6-9065-083e01fff5c8.png)
У тебя как раз нет тестов на размер, так что добавь их :)

А так в целом всё классно)

2022-04-30 13:53 UTC, GirZ0n commented on src/main/kotlin/Homework3/AVLTree.kt
> +    override var size = 0
Надо добавить приватный `set`, а то извне можно поменять размер дерева :)

2022-04-30 13:53 UTC, GirZ0n commented on src/main/kotlin/Homework3/AVLTree.kt
> +        }
C-style обход дерева) Кажется лучше перенести его в ноду и вызывать dfs от самой вершины. А сама функция будет возвращать список)

2022-04-30 13:53 UTC, GirZ0n commented on src/main/kotlin/Homework3/AVLTree.kt
> +        }
Если поправить `dfs`, то можно в одну строчку сделать :)

2022-04-30 13:53 UTC, GirZ0n commented on src/main/kotlin/Homework3/AVLTree.kt
> +        }
Аналогично с `values` и `keys`.

2022-04-30 13:53 UTC, GirZ0n commented on src/main/kotlin/Homework3/AVLTree.kt
> +        entries.clear()
Так как ты переопределил геттеры, то в этом нет необходимости)

2022-04-30 13:53 UTC, GirZ0n commented on src/main/kotlin/Homework3/AVLTree.kt
> +    }
Я немного запутался. У тебя же есть функция `get`, которая находит значение по ключу. Кажется, что ты можешь не возвращать вместе с нодой удаляемое значение, а просто отдельно в методе `remove` найти его. Или я не прав?)

2022-04-30 13:53 UTC, GirZ0n commented on src/main/kotlin/Homework3/AVLTree.kt
> +    }
Мне просто не нравится, что ты возвращаешь одновременно, и ноду, и значение) Кажется что лучше делать что-то одно)

2022-05-01 11:05 UTC, ArtyomKopan commented
Проблемка с балансом так и осталась, я уже и пробовал добавить функции rotateLeftRight и rotateRightLeft, но ничего не изменилось

2022-05-06 09:14 UTC, GirZ0n approved these changes
Я в 3 пункте тебе написал поправить дефолтные значения, но ты не везде это сделал :)
![image](https://user-images.githubusercontent.com/55441714/167103117-a6f754c0-3787-405e-82e6-895ab45af1b2.png)
Если это исправить, то вроде как всё верно будет работать)

2022-05-06 09:14 UTC, GirZ0n commented on src/main/kotlin/Homework3/AVLTreeNode.kt
> +    }
Немного c-style) Ты же можешь прямо внутри функции создать список, в которым будешь собирать все вершины.

2022-05-11 12:06 UTC, SpirinEgor approved these changes

2022-05-11 12:07 UTC, merged