Kotlin. Homework #4. Task #1
ArtyomKopan/Kotlin_HW pull request #6
Opened 2022-05-05 08:14 UTC by ArtyomKopan

2022-05-29 22:24 UTC, elena-lyulina requested changes
Выглядит неплохо, осталось сделать, чтобы работало...

2022-05-29 22:24 UTC, elena-lyulina commented on src/test/kotlin/Homework4/MergeSortTest.kt
> +            Arguments.of(Array(1000) { Random.nextInt() }, 16)
хочется больше тестов, а не вручную выбранные 15 вариантов) и попробуй с большими числами, чем 1000 элементов и 16 потоков

2022-05-29 22:24 UTC, elena-lyulina commented on src/main/kotlin/Homework4/plot.kt
> +fun main() {
на 1000000 элементах все падает :( так не должно быть

2022-05-29 22:24 UTC, elena-lyulina commented on src/test/kotlin/Homework4/MergeSortTest.kt
> +        assertEquals(true, ms.array.contentEquals(array.sortedArray()))
можно сразу использовать assertTrue

2022-05-29 22:24 UTC, elena-lyulina commented on src/main/kotlin/Homework4/plot.kt
> +    ggsave(fig, "plot$size.png")
было бы классно на самих графиках подписывать, что это вообще и какой размер массива был

2022-05-29 22:24 UTC, elena-lyulina commented on src/main/kotlin/Homework4/MergeSort.kt
> +                    Thread { MergeSort(array, maxThreadsCount, threadsCount++).multiThreadMergeSort(middle, right) }
подумай, сколько у тебя в действительности запускается потоков и равно ли это тому числу, которое должно быть?

2022-05-30 09:48 UTC, ArtyomKopan commented
Я пофиксил ошибку с числом потоков, теперь всё отлично работает и с >= 10^6 элементов. Также добавил новые графики для бОльших массивов

2022-05-30 09:49 UTC, elena-lyulina commented
а почини конфликты еще?

2022-05-30 11:28 UTC, ArtyomKopan commented
Починил

2022-06-01 11:23 UTC, ArtyomKopan commented
Починил ещё раз)

2022-06-01 12:01 UTC, elena-lyulina approved these changes
Класс! график на 1000000 элементов даже выглядит правдоподобно, что на 8 потоках работает лучше всего

2022-06-01 12:01 UTC, merged