Kotlin. Homework #5. Task #1
ArtyomKopan/Kotlin_HW pull request #7
Opened 2022-05-05 14:53 UTC by ArtyomKopan

2022-05-30 09:54 UTC, elena-lyulina requested changes
Выглядит неплохо, но хочется, чтобы это было продолжением предыдущей задачи, а не копированием :)

2022-05-30 09:54 UTC, elena-lyulina commented on src/main/kotlin/Homework5/plot.kt
> +fun main() {
хочется не копировать код из предыдущего дз, а встроить еще один режим в предыдущее задание
подумай сразу над архитектурой -- если у тебя есть две реализации одной и той же сортировки, то мб стоит сделать под них интерфейс и добавить разные реализации

2022-05-30 09:54 UTC, elena-lyulina commented on src/main/kotlin/Homework5/MergeSort.kt
> +    fun coroutineMergeSort(left: Int, right: Int) {
а количество запускаемых корутин ты где регулируешь?.... тут хочется такие же графики, как и с потоками, чтобы смотреть зависимость и от количества элементов, и от количества запущенных корутин

2022-05-30 09:54 UTC, elena-lyulina commented on src/test/kotlin/Homework5/MergeSortTest.kt
> +            Arguments.of(emptyArray<Int>()),
ну и с тестами тот же коммент, что и к дз4

2022-05-30 16:12 UTC, ArtyomKopan commented on src/main/kotlin/Homework5/plot.kt
> +fun main() {
а в какую ветку тогда лучше всё это пушить - в эту или ту, что с первой задачей?

2022-05-30 21:19 UTC, ArtyomKopan commented
Я переделал архитектуру, сделал с наследованием от интерфейса. И файлы из домашки на многопоточность тоже добавил сюда, с соответстующими изменениями (так что ту ветку, наверное, можно не сливать)

2022-06-01 11:29 UTC, ArtyomKopan commented
Починил ещё раз)

2022-06-01 12:03 UTC, elena-lyulina commented
> Я переделал архитектуру, сделал с наследованием от интерфейса. И файлы из домашки на многопоточность тоже добавил сюда, с соответстующими изменениями (так что ту ветку, наверное, можно не сливать)

хотела бы я это прочитать перед тем, как я слила ту ветку :) тебе теперь чинить конфликты, извиняюсь

2022-06-01 12:08 UTC, elena-lyulina requested changes

2022-06-01 12:08 UTC, elena-lyulina commented on src/main/kotlin/Homework5/CoroutineMergeSort.kt
> +                    val rightCoroutinesCount = floor(maxCoroutinesCount.toDouble() / 2).toInt()
в runBlocking лучше писать необходимый минимум действий) это же блокирующий запуск

2022-06-01 12:08 UTC, elena-lyulina commented on src/main/kotlin/Homework5/CoroutineMergeSort.kt
> +                    leftSorting.join()
а в чем смысл дожидаться предыдущей корутины и только потом начинать следующую?

2022-06-01 12:08 UTC, elena-lyulina commented on src/main/kotlin/Homework5/plot.kt
> +    ggsave(coroutineSortFigure, "coroutinePlot$size.png")
тут оч много повторений происходит,ты по два раза делаешь почти одно и то же
вынеси все максимально в функции и вызывай их

2022-06-01 12:08 UTC, elena-lyulina commented on src/test/kotlin/Homework5/MultithreadingMergeSortTest.kt
> +        fun addTestInputData(): List<Arguments> {
чтобы это не копировать, можно тесты для потоков и корутин запускать из одного класса, просто разными тестами

2022-06-01 13:48 UTC, ArtyomKopan commented
Всё исправил

2022-06-01 13:49 UTC, ArtyomKopan commented
Правда, когда я делал `git pull origin main`, из-за конфликтов слияния сюда затесались файлы из других домашек(

2022-06-02 11:35 UTC, elena-lyulina approved these changes
Хорошо, поправь конфликты и я солью)

2022-06-02 12:28 UTC, merged